jobs:
  - name: ecsmanifest908
    type: manifest
    steps:
      - GET: triggertest1
      - GET: new-imagenode2
      
  - name: script-piperf30
    type: runSh
   # serial: true
    steps:
      - GET: sample-script1
      - GET: triggertest1
      - TASK:
        - script: pwd
        - script: ./GET/sample-script/sample-script/echo.sh
        
  - name: script-piperunShpf40
    type: runSh
    serial: true
    steps:
      - GET: sample-script1
      - GET: triggertest1
      - TASK:
        - script: ls
        - script: ./GET/sample-script/sample-script/echo.sh
  #- name: script-p333
    #type: runSh
    #serial: true
     #steps:
      #- GET: sample-script1
      #- GET: triggertest1  
      #- TASK:
       # - script: ps
        #- script: ./GET/sample-script/sample-script/echo.sh
 

