jobs:
  #- name: ecsmanifestv1
   # type: manifest
  #  steps:
      #- GET: triggertest1
    #  - GET: new-imagenode2
      
  - name: privatescript1
    type: runSh
   # serial: true
    steps:
      - IN: sample-privatescript1
      - IN: triggertest
      #- GET: triggertest
      - TASK:
        - script: pwd
        - script: ./IN/sample-privatescript1/sample-privatescript1/echo.sh
        
  #- name: script-piperunShv3
   # type: runSh
  #  serial: true
   # steps:
    #  - GET: sample-script2
     # - GET: triggertest
      #- TASK:
       # - script: ls
      #  - script: ./GET/sample-script/sample-script/echo.sh
  #- name: script-p333
    #type: runSh
    #serial: true
     #steps:
      #- GET: sample-script1
      #- GET: triggertest1  
      #- TASK:
       # - script: ps
        #- script: ./GET/sample-script/sample-script/echo.sh
 

